### ISSUE TITLE
希望引用博客中的部分demo

### ISSUE THREAD

**Issue by zhu-xiaoming** [malcolm-kee/malcolm-kee#146]
你好，我最近要在公司团队内部分享中，介绍View Transitions，在搜索 View Transitions 相关的文章时，找到了你的文章https://malcolmkee.com/blog/view-transition-api-in-react-app/。

我想要引用你的文章中的部分demo，希望取得你的授权，谢谢🙏。

由于没有找到你的邮箱地址，只能把请求发到issue了，如果有问题，你可以关闭它。

**Comment by malcolm-kee** [comment]
没问题👍🏻
